package dev.crlhitbox.api.entity;

import dev.crlhitbox.api.event.EntityColliderUpdateEvent;
import dev.crlhitbox.internal.entity.EntityColliderCapability;
import dev.crlhitbox.internal.entity.EntityColliderThreads;
import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.common.MinecraftForge;

import java.util.Objects;
import java.util.Optional;

/**
 * Public access to an Entity's already-attached CRL Hitbox collider cache.
 *
 * <p>The cache accepts every supported collider kind, including finite rays and compounds. This
 * utility never creates, attaches, persists, or synchronizes capability state; {@link #find} and
 * {@link #require} only read the cache that the capability provider already owns.</p>
 */
public final class EntityColliders {
    private EntityColliders() {
    }

    /** Finds the already-attached cache without creating or mutating capability state. */
    public static Optional<EntityColliderHolder> find(Entity entity) {
        Objects.requireNonNull(entity, "entity");
        return EntityColliderCapability.find(entity);
    }

    /** Returns the attached cache or fails when capability attachment is absent. */
    public static EntityColliderHolder require(Entity entity) {
        return find(entity).orElseThrow(() -> new IllegalStateException(
                "Entity does not have the CRL Hitbox entity_colliders capability"));
    }

    /**
     * Posts one explicit update entry for {@code entity} and reports whether the cache changed.
     *
     * <p>The call must already be on the logical game thread that owns the cache; it does not
     * dispatch, and it never runs from a query or a renderer. It captures the current contents,
     * publishes {@link EntityColliderUpdateEvent} synchronously once, and then compares the cache
     * revision: listeners publish new snapshots themselves, so nothing is generated by default and
     * nothing is sent over the network. The return value is whether the revision actually advanced,
     * so a listener that decided nothing changed reports {@code false}.</p>
     *
     * <p>Recursive requests for the same entity are rejected, and the reentrancy marker is always
     * cleared without replacing a listener's original failure. A listener exception propagates to the
     * caller; earlier publications by other listeners are not rolled back, so a listener that needs
     * batch atomicity builds one snapshot and calls {@code replaceContents} once.</p>
     *
     * @param entity the entity whose cache should be updated
     * @param reason a caller-defined reason identifier
     * @return whether the cache revision changed
     */
    public static boolean requestUpdate(Entity entity, ResourceLocation reason) {
        Objects.requireNonNull(entity, "entity");
        Objects.requireNonNull(reason, "reason");
        EntityColliderThreads.requireLogicalThread(entity);
        EntityColliderHolder holder = require(entity);
        if (holder.updateInProgress) {
            throw new IllegalStateException(
                    "recursive collider update requested for the same entity");
        }
        EntityColliderSnapshot before = holder.snapshot();
        long beforeRevision = before.revision();
        holder.updateInProgress = true;
        try {
            MinecraftForge.EVENT_BUS.post(
                    new EntityColliderUpdateEvent(entity, reason, holder, before));
        } finally {
            holder.updateInProgress = false;
        }
        return holder.revision() != beforeRevision;
    }
}
